### ISSUE TITLE
Shortcut ALT+OPT+G collides with TextSearch

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/TrackGit#13]
In the rdef:
resource("BEOS:default_shortcut") "G";

collides with the TextSearch add-on's shortcut.
Also, why is there a shortcut at all? All it does for me is show an alert that TrackGit is a Tracker add-on...

**Comment by JadedCtrl** [comment]
Cleared out with b676c5e0ed241a88ed358f0dc73cfa3fa065d76e.

**Comment by jsteinaker** [comment]
This is probably ready to close now.

**Comment by humdingerb** [comment]
Long overdue... :)
