### ISSUE TITLE
Fix build for gcc7

### ISSUE THREAD

**Issue by Begasus** [HaikuArchives/TrackGit#3]
A recipe has been created for TrackGit (https://github.com/haikuports/haikuports/pull/3158)  but it only builds on gcc2, could use some looking into

**Comment by Begasus** [comment]
In Utils.h there is a call for Vector.h which is only available on gcc2 afaikt

**Comment by andimachovec** [comment]
This issue should be solved by my pull requests which were already merged

**Comment by Begasus** [comment]
> This issue should be solved by my pull requests which were already merged

Indeed, should've deleted the previous comment, thanks for the fix!

**Comment by Begasus** [comment]
This can be closed :)
